// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
