services:
  db:
    image: postgres:16-alpine
    container_name: devodoro-db
    environment:
      POSTGRES_DB: devodoro
      POSTGRES_USER: devodoro
      POSTGRES_PASSWORD: devodoro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: